# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "/common-util"
      - "/Idfdata-service"
      - "/investigation-service"
      - "/liquibase-service"
      - "/observation-service"
      - "/organization-service"
      - "/person-service"
      - "/post-processing-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directories:
      - "/Idfdata-service"
      - "/investigation-service"
      - "/liquibase-service"
      - "/observation-service"
      - "/organization-service"
      - "/person-service"
      - "/post-processing-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]